### ISSUE TITLE
7zip file in Readme.md is corrupted by 'Save link as ...'

### ISSUE THREAD

**Issue by pmcgee69** [OscarL/MatrixSS#1]
Release 1.0 ---->  https://github.com/OscarL/MatrixSS/releases/download/v1.0/MatrixSS.7z (65kb)

Readme.md --->  https://github.com/OscarL/MatrixSS/blob/master/MatrixSS.7z  
(196kb with right-click save link as,  Maybe this is a github issue? Click on link + raw = correct download)

**Comment by OscarL** [comment]
Hello there! Thanks for checking out MatrixSS!.

Can confirm the issue here, (using Win10 + Firefox 107.0).

Welp... second link is NOT a direct link to the .7z (despite it's URL, and as a normal user would expect), but to an HTML... that's what the "corrupted .7z file" of almost 200 KB actually is (you can open it with notepad.exe), as the browser indeed sees an HTML document.

In any case... fixed it by changing the link to the release archive URL.

Thanks again for the heads up!

**Comment by pmcgee69** [comment]
Nice. No problem. 👍
